// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCenter.h"
#include "Commands/AutonomousLeft.h"
#include "Commands/AutonomousRight.h"
#include "Commands/DriveToCube.h"
#include "Commands/DriveToScale.h"
#include "Commands/DriveToSwitch.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/PositionArm.h"
#include "Commands/PositionElevator.h"
#include "Commands/RunIntake.h"
#include "Commands/ScoreOnScale.h"
#include "Commands/ScoreOnScaleThenSwitch.h"
#include "Commands/ScoreOnSwitch.h"
#include "Commands/ScoreOnSwitchThenScale.h"
#include "Commands/ScoreTwice.h"
#include "Commands/StartFieldPositioningSystem.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

#include "Commands/PickupCube.h"

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driverJoystick.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("RunIntake", new RunIntake());
    frc::SmartDashboard::PutData("DriveToSwitch", new DriveToSwitch());
    frc::SmartDashboard::PutData("DriveToScale", new DriveToScale());
    frc::SmartDashboard::PutData("DriveToCube", new DriveToCube());
    frc::SmartDashboard::PutData("ScoreOnScaleThenSwitch", new ScoreOnScaleThenSwitch());
    frc::SmartDashboard::PutData("ScoreOnSwitchThenScale", new ScoreOnSwitchThenScale());
    frc::SmartDashboard::PutData("ScoreOnScale", new ScoreOnScale());
    frc::SmartDashboard::PutData("ScoreOnSwitch", new ScoreOnSwitch());
    frc::SmartDashboard::PutData("AutonomousRight", new AutonomousRight());
    frc::SmartDashboard::PutData("AutonomousCenter", new AutonomousCenter());
    frc::SmartDashboard::PutData("AutonomousLeft", new AutonomousLeft());
    frc::SmartDashboard::PutData("DriveWithJoystick", new DriveWithJoystick());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    frc::SmartDashboard::PutData("PickupCube", new PickupCube());
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriverJoystick() {
   return driverJoystick;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
