// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include <RobotMap.h>
#include "LiveWindow/LiveWindow.h"
#include "ctre/Phoenix.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX1;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX3;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX5;
std::shared_ptr<frc::SpeedControllerGroup> RobotMap::driveTrainSpeedControllerGroupLeft;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX2;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX4;
std::shared_ptr<WPI_TalonSRX> RobotMap::driveTrainTalonSRX6;
std::shared_ptr<frc::SpeedControllerGroup> RobotMap::driveTrainSpeedControllerGroupRight;
std::shared_ptr<frc::RobotDrive> RobotMap::driveTrainRobotDrive;
std::shared_ptr<frc::DoubleSolenoid> RobotMap::grippergripper;
std::shared_ptr<WPI_TalonSRX> RobotMap::gripperIntakeTalonSRX10;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

std::shared_ptr<frc::Compressor> RobotMap::compressor20;
std::shared_ptr<frc::DoubleSolenoid> RobotMap::driveTrainShifterDoubleSolenoidLeft;
std::shared_ptr<frc::DoubleSolenoid> RobotMap::driveTrainShifterDoubleSolenoidRight;

std::shared_ptr<WPI_TalonSRX> RobotMap::elevatorTalonSRX7;
std::shared_ptr<WPI_TalonSRX> RobotMap::elevatorTalonSRX8;
std::shared_ptr<WPI_TalonSRX> RobotMap::armTalonSRX9;
std::shared_ptr<AHRS> RobotMap::ahrs;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    frc::LiveWindow *lw = frc::LiveWindow::GetInstance();

    driveTrainTalonSRX1.reset(new WPI_TalonSRX(1));
    
    
    driveTrainTalonSRX3.reset(new WPI_TalonSRX(3));
    
    
    driveTrainTalonSRX5.reset(new WPI_TalonSRX(5));
    
    
    driveTrainSpeedControllerGroupLeft = std::make_shared<frc::SpeedControllerGroup>(*driveTrainTalonSRX1, *driveTrainTalonSRX3 , *driveTrainTalonSRX5 );
    lw->AddActuator("DriveTrain", "Speed Controller Group Left", driveTrainSpeedControllerGroupLeft);
    
    driveTrainTalonSRX2.reset(new WPI_TalonSRX(2));
    
    
    driveTrainTalonSRX4.reset(new WPI_TalonSRX(4));
    
    
    driveTrainTalonSRX6.reset(new WPI_TalonSRX(6));
    
    
    driveTrainSpeedControllerGroupRight = std::make_shared<frc::SpeedControllerGroup>(*driveTrainTalonSRX2, *driveTrainTalonSRX4 , *driveTrainTalonSRX6 );
    lw->AddActuator("DriveTrain", "Speed Controller Group Right", driveTrainSpeedControllerGroupRight);
    
    driveTrainRobotDrive.reset(new frc::RobotDrive(driveTrainSpeedControllerGroupLeft, driveTrainSpeedControllerGroupRight));
    
    driveTrainRobotDrive->SetSafetyEnabled(true);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);

        driveTrainRobotDrive->SetInvertedMotor(frc::RobotDrive::kRearRightMotor, true);
    grippergripper.reset(new frc::DoubleSolenoid(0, 0, 1));
    lw->AddActuator("Gripper", "gripper", grippergripper);
    
    gripperIntakeTalonSRX10.reset(new WPI_TalonSRX(10));
    
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    //compressor20 = std::make_unique<frc::Compressor>(20);
    compressor20.reset(new Compressor(20));
    compressor20->SetClosedLoopControl(true);


    //driveTrainShifterDoubleSolenoidLeft = std::make_unique<frc::DoubleSolenoid>(0,1);
    driveTrainShifterDoubleSolenoidLeft.reset(new DoubleSolenoid(0,1));

    //driveTrainShifterDoubleSolenoidRight = std::make_unique<frc::DoubleSolenoid>(2,3);
    driveTrainShifterDoubleSolenoidRight.reset(new DoubleSolenoid(2,3));


    driveTrainShifterDoubleSolenoidLeft->Set(frc::DoubleSolenoid::Value::kOff);
    driveTrainShifterDoubleSolenoidRight->Set(frc::DoubleSolenoid::Value::kOff);


    elevatorTalonSRX7 = std::make_unique<WPI_TalonSRX>(7);
    elevatorTalonSRX8 = std::make_unique<WPI_TalonSRX>(8);
    armTalonSRX9 = std::make_unique<WPI_TalonSRX>(9);

    ahrs = std::make_unique<AHRS>(frc::SPI::Port::kMXP);
}
