// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "AutonomousCommand.h"
#include "../Robot.h"

AutonomousCommand::AutonomousCommand(char initialPos, char initialMove, char change1, char score1, char change2, char score2): frc::Command() {
//	findPosition = new AutonomousFindPosition(true);
	initialTurntoSwitch = new AutonomousTurnToTarget(true);
	position = initialPos;
	switches = 'LRL';
}

void AutonomousCommand::Initialize() {
//	findPosition->Start();

	// move forward ~1 meter
	// turn to the switch
	// point gimbal 45 degrees
	// follow the switch around
}

void AutonomousCommand::Execute() {
//	if (findPosition->IsCompleted()) {
//		position = findPosition->GetPosition();
//	}
}

bool AutonomousCommand::IsFinished() {
    return false;
}

void AutonomousCommand::End() {

}

void AutonomousCommand::Interrupted() {

}
