// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "AutonomousCommand.h"
#include "../Robot.h"

AutonomousCommand::AutonomousCommand(int initial, int change1, int score1, int change2, int score2): frc::Command() {
	findPosition = new AutonomousFindPosition();
}

void AutonomousCommand::Initialize() {
//	autonomousScoreScale = new AutonomousScoreScale();
//	autonomousScoreSwitch = new AutonomousScoreSwitch();

	findPosition->Start();
}

void AutonomousCommand::Execute() {
	if (findPosition->IsCompleted()) {
		position = findPosition->GetPosition();
	}
}

bool AutonomousCommand::IsFinished() {
    return false;
}

void AutonomousCommand::End() {

}

void AutonomousCommand::Interrupted() {

}
