
#include "OpenGripper.h"


OpenGripper::OpenGripper() : frc::TimedCommand(timeToOpen) {
	Requires(Robot::gripper.get());
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void OpenGripper::Initialize() {

}

// Called repeatedly when this Command is scheduled to run
void OpenGripper::Execute() {
}

// Called once after command times out
void OpenGripper::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void OpenGripper::Interrupted() {

}
