// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "PickupCube.h"
#include "Commands/CommandGroupBuilder.h"
#include "Commands/DriveToCube.h"
#include "Commands/OpenGripper.h"
#include "Commands/CloseGripper.h"
#include "Commands/RunIntake.h"
#include "Commands/PositionElevator.h"
#include "Commands/PositionArm.h"

PickupCube::PickupCube()
{
	auto prepArmForPickup = BuildSequential({
			BuildParallel({ new PositionElevator(0), new PositionArm(PositionArm::Position::Pickup) }),
			BuildParallel({ new OpenGripper(), new RunIntake() })
	});

	AddSequential(BuildParallel({ new DriveToCube(), prepArmForPickup }));
	AddSequential(new CloseGripper());
}
