// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctre/Phoenix.h"


#include "DriveTrainShifter.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

DriveTrainShifter::DriveTrainShifter() : frc::Subsystem("DriveTrainShifter") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    shifter = RobotMap::driveTrainShifterDS;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void DriveTrainShifter::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void DriveTrainShifter::Periodic() {
    // Put code here to be run every loop


}

void DriveTrainShifter::ShiftHigh() {

	shifter->Set(frc::DoubleSolenoid::Value::kForward);

}

void DriveTrainShifter::ShiftLow() {

	shifter->Set(frc::DoubleSolenoid::Value::kReverse);

}

/*frc::DoubleSolenoid::Value DriveTrainShifter::GetGear() {

	if (shifterLeft->Get() == shifterRight->Get()) {
		return shifterLeft->Get();
	} else {
		return frc::DoubleSolenoid::Value::kForward;
	}

}*/

// Put methods for controlling this subsystem
// here. Call these from Commands.

