// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "ctre/Phoenix.h"


#include "DriveTrainShifter.h"
#include "../RobotMap.h"

DriveTrainShifter::DriveTrainShifter() :
	frc::Subsystem("DriveTrainShifter"),
	m_left(RobotMap::driveTrainTalonSRX1, std::chrono::milliseconds(10)),
	m_right(RobotMap::driveTrainTalonSRX2, std::chrono::milliseconds(10))
{
    shifter = RobotMap::driveTrainShifterDS;
	ShiftLow();
}

void DriveTrainShifter::ShiftHigh()
{
	shifter->Set(frc::DoubleSolenoid::Value::kForward);
	m_left.Start();
	m_right.Start();
	m_count = 20;
}

void DriveTrainShifter::ShiftLow()
{
	shifter->Set(frc::DoubleSolenoid::Value::kReverse);
	m_left.Start();
	m_right.Start();
	m_count = 20;
}

bool DriveTrainShifter::IsShiftDone() const
{
	return --m_count < 0;
}

void DriveTrainShifter::FinishShift()
{
	m_left.Stop();
	m_right.Stop();
}
